-- +migrate Up
CREATE TABLE tasks
(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title varchar NOT NULL,
	description varchar NOT NULL,
	status varchar NOT NULL
);

-- +migrate Down
DROP TABLE tasks;